import { InMemoryDbService } from 'angular-in-memory-web-api';

//import * as citiesOfBulgaria from '../assets/api/citiesOfBulgaria.json';
//import * as allCities from '../assets/api/allCities.json';
//import * as latestReviews from '../assets/api/latestReviews.json';

export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        const citiesOfBulgaria = [
            { id: 1, name: 'Албена', count_realty: 5 },
            { id: 2, name: 'Ахелой', count_realty: 24 },
            { id: 3, name: 'Ахтополь', count_realty: 3 },
            { id: 4, name: 'Боровец', count_realty: 1 },
            { id: 5, name: 'Бургас', count_realty: 41 },
            { id: 6, name: 'Банско', count_realty: 48 },
            { id: 7, name: 'Бяла', count_realty: 2 },
            { id: 8, name: 'Балчик', count_realty: 17 },
            { id: 9, name: 'Бяла', count_realty: 53 },
            { id: 10, name: 'Велико Тарново', count_realty: 2 },
            { id: 11, name: 'Варна', count_realty: 72 },
            { id: 12, name: 'Велинград', count_realty: 1 },
            { id: 13, name: 'Габрово', count_realty: 1 },
            { id: 14, name: 'Добрич', count_realty: 1 },
            { id: 15, name: 'Елените', count_realty: 65 },
            { id: 16, name: 'Золотые Пески', count_realty: 65 },
            { id: 17, name: 'Кранево', count_realty: 7 },
            { id: 18, name: 'Каварна', count_realty: 1 },
            { id: 19, name: 'Кошарица', count_realty: 5 },
            { id: 20, name: 'Китен', count_realty: 2 },
            { id: 21, name: 'Каблешково', count_realty: 1 },
            { id: 22, name: 'Лозенец', count_realty: 12 },
            { id: 23, name: 'Несебр', count_realty: 108 },
            { id: 24, name: 'Обзор', count_realty: 29 },
            { id: 25, name: 'область Благоевград, Разлог', count_realty: 1 },
            { id: 26, name: 'Пловдив', count_realty: 1 },
            { id: 27, name: 'Поморие', count_realty: 167 },
            { id: 28, name: 'Приморско', count_realty: 26 },
            { id: 29, name: 'Пампорово', count_realty: 17 },
            { id: 30, name: 'Равда', count_realty: 126 },
            { id: 31, name: 'Рогачево', count_realty: 1 },
            { id: 32, name: 'Сандански', count_realty: 7 },
            { id: 33, name: 'София', count_realty: 4 },
            { id: 34, name: 'Святой Влас', count_realty: 511 },
            { id: 35, name: 'Солнечный берег', count_realty: 539 },
            { id: 36, name: 'Сарафово', count_realty: 35 },
            { id: 37, name: 'Созополь', count_realty: 103 },
            { id: 38, name: 'Св. Константин и Елена', count_realty: 7 },
            { id: 39, name: 'Синеморец', count_realty: 1 },
            { id: 40, name: 'Царево', count_realty: 6 },
            { id: 41, name: 'Черноморец', count_realty: 13 },
            { id: 42, name: 'Шабла', count_realty: 1 }
        ];
        const allCities = [
            { id: 1262, name: 'Афины', country: 'Греция', count_realty: 4 },
            { id: 4055, name: 'Анапа', country: 'Россия', count_realty: 1 },
            { id: 15789615, name: 'Аланья', country: 'Турция', count_realty: 2 },
            { id: 1733, name: 'Барселона', country: 'Испания', count_realty: 8 },
            { id: 15789559, name: 'Будва', country: 'Черногория', count_realty: 5 },
            { id: 15789578, name: 'Бенидорм', country: 'Испания', count_realty: 3 },
            { id: 1743, name: 'Валенсия', country: 'Испания', count_realty: 1 },
            { id: 7593157, name: 'Гирне', country: 'Кипр', count_realty: 1 },
            { id: 2541, name: 'Друскининкай', country: 'Литва', count_realty: 1 },
            { id: 5198, name: 'Домбай', country: 'Россия', count_realty: 1 },
            { id: 15789580, name: 'Дения', country: 'Испания', count_realty: 1 },
            { id: 1273, name: 'Ираклион', country: 'Греция', count_realty: 1 },
            { id: 4049790, name: 'Иматра', country: 'Финляндия', count_realty: 1 },
            { id: 15789600, name: 'Коста Адехе Тенерифе', country: 'Испания', count_realty: 2 },
            { id: 15789608, name: 'Криопиги', country: 'Греция', count_realty: 2 },
            { id: 2299, name: 'Лимассол', country: 'Кипр', count_realty: 3 },
            { id: 15789599, name: 'Лос Гигантэс Тенерифе', country: 'Испания', count_realty: 3 },
            { id: 157896324, name: 'Лутракион', country: 'Греция', count_realty: 4 },
            { id: 15789588, name: 'Марбелья', country: 'Испания', count_realty: 1 },
            { id: 157896325, name: 'Метаморфоси', country: 'Греция', count_realty: 2 },
            { id: 157896349, name: 'Мармарис', country: 'Турция', count_realty: 1 },
            { id: 10398, name: 'Одесса', country: 'Украина', count_realty: 1 },
            { id: 15789590, name: 'Ориуэла Коста', country: 'Испания', count_realty: 1 },
            { id: 1770, name: 'Палма-де-Мальорка', country: 'Испания', count_realty: 2 },
            { id: 1853, name: 'Палермо', country: 'Италия', count_realty: 3 },
            { id: 15789561, name: 'Пхукет', country: 'Тайланд', count_realty: 2 },
            { id: 15789570, name: 'Пафос', country: 'Кипр', count_realty: 3 },
            { id: 15789591, name: 'Плая де лас Америкас', country: 'Испания', count_realty: 6 },
            { id: 15789598, name: 'Пинеда де Мар', country: 'Испания', count_realty: 1 },
            { id: 1809, name: 'Реджио-ди-Калабриа', country: 'Италия', count_realty: 1 },
            { id: 4440, name: 'Серпухов', country: 'Россия', count_realty: 1 },
            { id: 4962, name: 'Санкт-Петербург', country: 'Россия', count_realty: 1 },
            { id: 1344, name: 'Тбилиси', country: 'Грузия', count_realty: 10 },
            { id: 15789595, name: 'Торревьеха', country: 'Испания', count_realty: 5 },
            { id: 1269, name: 'Ханья', country: 'Греция', count_realty: 4 },
            { id: 7718652, name: 'Ханты-Мансийск', country: 'Россия', count_realty: 1 },
            { id: 15789602, name: 'Халкидики', country: 'Греция', count_realty: 3 },
            { id: 15789620, name: 'Элеонас', country: 'Греция', count_realty: 1 },
            { id: 2508, name: 'Юрмала', country: 'Латвия', count_realty: 2 }
        ];
        return {citiesOfBulgaria, allCities};
    }
}